version: '3'

networks:
  docker-develop-env-share:
    driver: bridge

services:
  mysql:
    networks:
      - docker-develop-env-share
    build:
      context: ./dockers/mysql
    ports:
      - "5306:3306"
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=!PTERq9NaN*+BMkePJu5
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=PGQ1BL)N-j!*L-a!cvTV
    cap_add:
      - ALL
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./dockers/misc/mysql/data:/var/lib/mysql
      - ./dockers/misc/mysql/log:/var/log/mysql
      - ./dockers/mysql/common.cnf:/etc/mysql/my.cnf
      - ./dockers/mysql/master.cnf:/etc/mysql/conf.d/my.cnf
      - ./dockers/mysql/init.sh:/docker-entrypoint-initdb.d/000-init.sh

  base:
    networks:
      - docker-develop-env-share
    build: ./dockers/base
    ports:
      - "1080:80"
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
      - LANGUAGE=ja_JP:ja
      - LC_ALL=ja_JP.UTF-8
    privileged: true
    volumes:
      - ./dockers/base/php-fpm/php.ini:/etc/php/php.ini
      - ./dockers/base/php-fpm/php-fpm.conf:/etc/php-fpm.conf
      - ./dockers/base/php-fpm/www.conf:/etc/php-fpm.d/www.conf
      - ~/.ssh:/root/.ssh
      - ~/.ssh:/home/ec2-user/.ssh
      - ./dockers/misc/nginx/log:/var/log/nginx
      - ./dockers/misc/php-fpm/log:/var/log/php-fpm
      - ./dockers/base/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dockers/base/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dockers/base/nginx/realip.conf:/etc/nginx/conf.d/realip.conf
      - ./work:/home/ec2-user/work
      - ./public:/var/www/public
